package rules;

import com.ftn.sbnz.backward.model.models.Location;
import com.ftn.sbnz.backward.model.models.Watch;
import com.ftn.sbnz.backward.model.models.Question;
import com.ftn.sbnz.backward.model.models.Recommendation;

global com.ftn.sbnz.backward.kjar.IQuestionRepository questionRepository;
global com.ftn.sbnz.backward.model.models.Question nextQuestion;

rule "questionnaireStart" salience 20
    when
        not (Question())
    then
        insert(questionRepository.findById(1L).get());
end

rule "nextQuestion" salience 1
when
    $question: Question(!isAnswered())
    not (Question(priority > $question.priority && !isAnswered()))
then
    nextQuestion = $question;
end
